### ISSUE TITLE
yab 1.7.6 is not backward compatible

### ISSUE THREAD

**Issue by bbjimmy** [bbjimmy/YAB#9]

**Comment by lorglas** [comment]
Hello, yes it is right. The transparency must be set in the programs that need this feature adjusted. Unfortunately, it was not possible to change, because the transparency in the old version of yab was not properly implemented. I think we are not so many yab programmers and to my knowledge, there are not so many programs that use this feature, so that it is quite reasonable that the programmers rework their programs at this point. But also unsightly graphics errors are resolved.
